import {topicRows,esc} from './utils.js';
import {weakTopics,accuracyByTopic} from '../engine/analytics.js';
import {readiness} from '../engine/readiness.js';
export default {id:'analytics',title:'Analytics',icon:'◉',exams:['dsssb','bpsc'],route:'#/analytics',
render(el,ctx){
 const rows=topicRows(ctx.catalog,ctx.exam),ts=ctx.state.topicState||{},weights=Object.fromEntries(rows.map(x=>[x.id,x.priority==='A+'?4:x.priority==='A'?3:x.priority==='B'?2:1])), r=readiness(Object.fromEntries(rows.map(x=>[x.id,ts[x.id]||{mastery:.3,attempts:0}])),weights),atts=(ctx.state.attempts||[]).filter(x=>x.exam===ctx.exam),acc=accuracyByTopic(atts),weak=weakTopics(Object.fromEntries(rows.map(x=>[x.id,ts[x.id]||{mastery:.3}])),atts,weights);
 el.innerHTML='<div class="grid"><div class="card"><span class="small">Adjusted readiness</span><div class="kpi">'+r.score+'%</div></div><div class="card"><span class="small">Evidence coverage</span><div class="kpi">'+Math.round(r.coverage*100)+'%</div></div><div class="card"><span class="small">Attempts</span><div class="kpi">'+atts.length+'</div></div><div class="card"><span class="small">Accuracy</span><div class="kpi">'+(atts.length?Math.round(atts.filter(a=>a.correct).length/atts.length*100):0)+'%</div></div></div>'+
 '<div class="grid-2"><div class="card"><h3>Weak-topic queue</h3>'+(weak.length?weak.map(x=>'<div class="stat-row"><span><b>'+esc(x.topicId)+'</b><br><span class="muted">rank '+Math.round(x.rank*100)+'</span></span><b>'+Math.round((x.mastery??.3)*100)+'%</b></div>').join(''):'<div class="empty">Not enough evidence yet. Weak-topic detection activates after sufficient attempts.</div>')+'</div><div class="card"><h3>Topic accuracy</h3>'+Object.entries(acc).slice(0,15).map(([k,v])=>'<div class="stat-row"><span>'+esc(k)+'</span><b>'+Math.round(v.accuracy*100)+'%</b></div>').join('')+'</div></div>'+
 '<div class="card"><h3>How readiness is calculated</h3><p class="muted">Weighted topic mastery is adjusted by evidence coverage. Topics with fewer than five attempts are shown as early estimates rather than treated as fully measured.</p><p><b>'+esc(r.explanation)+'</b></p></div>';
 return el.innerHTML;
}};