import {topicRows,esc} from './utils.js';
import {predict} from '../engine/predictor.js';
export default {id:'mocks',title:'Mock Tests',icon:'◈',exams:['dsssb','bpsc'],route:'#/mocks',
render(el,ctx){
 const mocks=(ctx.state.mocks||[]).filter(x=>x.exam===ctx.exam),qs=(ctx.state.questions||[]).filter(q=>q.examTags?.includes(ctx.exam));
 const p=predict(mocks,Number(ctx.state.settings?.mockMaxMarks||200));
 el.innerHTML='<div class="grid-2"><div class="card"><h3>Mock Test Builder</h3><p class="muted">Build a timed test from your verified question bank. Configure marking because the official scheme must be confirmed for the target notification.</p><div class="toolbar"><label class="field">Questions<input id="mockN" type="number" min="1" max="'+qs.length+'" value="'+Math.min(20,qs.length||1)+'"></label><label class="field">Marks / correct<input id="mockMark" type="number" step=".25" value="'+(ctx.state.settings?.mockMark??1)+'"></label><label class="field">Negative / wrong<input id="mockNeg" type="number" step=".05" value="'+(ctx.state.settings?.mockNeg??0.25)+'"></label><label class="field">Minutes<input id="mockTime" type="number" value="30"></label></div><button id="startMock" class="btn primary" '+(!qs.length?'disabled':'')+'>Start mock</button></div><div class="card"><h3>Mock prediction</h3><div class="kpi">'+(p.ready?Math.round(p.mean)+' / '+(ctx.state.settings?.mockMaxMarks||200):'—')+'</div><p class="muted">'+(p.ready?'Range '+Math.round(p.low)+'–'+Math.round(p.high):'Not enough mocks. Complete 3+ mocks to show a weighted range.')+'</p></div></div>'+
 '<div class="card"><h3>Recent mocks</h3>'+(!mocks.length?'<div class="empty">No mock results yet.</div>':'<div class="table-wrap"><table><tr><th>Date</th><th>Score</th><th>Accuracy</th><th>Duration</th><th>Negative lost</th></tr>'+mocks.slice().reverse().map(m=>'<tr><td>'+new Date(m.timestamp).toLocaleString()+'</td><td><b>'+m.score+'</b> / '+m.maxMarks+'</td><td>'+Math.round(m.correct/Math.max(1,m.attempted)*100)+'%</td><td>'+m.duration+'m</td><td>'+m.negativeLost+'</td></tr>').join('')+'</table></div>')+'</div>';
 el.querySelector('#startMock')?.addEventListener('click',()=>start(el,ctx,qs));
 return el.innerHTML;
}};
function start(el,ctx,qs){
 const n=Math.min(qs.length,Math.max(1,Number(el.querySelector('#mockN').value||20))),pool=qs.slice().sort(()=>Math.random()-.5).slice(0,n);
 let i=0,answers={},started=Date.now(),duration=Number(el.querySelector('#mockTime').value||30),timer;
 const marks=Number(el.querySelector('#mockMark').value||1),neg=Number(el.querySelector('#mockNeg').value||0.25);
 const draw=()=>{if(i>=pool.length)return finish();const q=pool[i];el.innerHTML='<div class="card"><div class="section-head"><b>Question '+(i+1)+' / '+pool.length+'</b><span id="mt" class="danger">'+duration+':00</span></div><div class="question">'+esc(q.text)+'</div>'+q.options.map((o,k)=>'<button class="option" data-a="'+k+'">'+String.fromCharCode(65+k)+'. '+esc(o)+'</button>').join('')+'<div class="toolbar"><button id="skip" class="btn">Skip</button></div></div>';el.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{answers[i]=Number(b.dataset.a);i++;draw()});el.querySelector('#skip').onclick=()=>{i++;draw()};clearInterval(timer);let sec=duration*60;timer=setInterval(()=>{sec--;const t=el.querySelector('#mt');if(t)t.textContent=Math.floor(sec/60)+':'+String(sec%60).padStart(2,'0');if(sec<=0){clearInterval(timer);finish()}},1000)};
 const finish=()=>{clearInterval(timer);let correct=0,wrong=0,attempted=0,negLost=0;pool.forEach((q,k)=>{if(answers[k]===undefined)return;attempted++;if(answers[k]===Number(q.answer))correct++;else{wrong++;negLost+=neg}});const score=correct*marks-negLost;const sectionStats={};pool.forEach((q,k)=>{const section=q.section||String(q.topicId||'').split(':')[1]||'Other';sectionStats[section]??={attempted:0,correct:0,wrong:0,seconds:0,easyMisses:0};if(answers[k]!==undefined){sectionStats[section].attempted++;if(answers[k]===Number(q.answer))sectionStats[section].correct++;else{sectionStats[section].wrong++;if(Number(q.difficulty||3)<=2)sectionStats[section].easyMisses++}}});const result={id:crypto.randomUUID(),exam:ctx.exam,timestamp:Date.now(),score,maxMarks:pool.length*marks,correct,wrong,attempted,unattempted:pool.length-attempted,duration:Math.round((Date.now()-started)/60000),negativeLost:Number(negLost.toFixed(2)),sectionStats};ctx.state.mocks.push(result);ctx.state.lastMock=result;ctx.save();ctx.toast('Mock submitted');ctx.render()};draw();
}