(()=>{
'use strict';
const $=id=>document.getElementById(id);
const STATUS=['⬜ Not Started','🟨 Studying','🟦 Notes Done','🟩 PYQ Done','⭐ Mastered'];
const EX=[['DSSSB CS','dsssbTech'],['DSSSB Paper 1','dsssbPaper1'],['BPSC CS','bpscSubject'],['BPSC Prelims','bpscPrelims'],['BPSC Paper 1','bpscMainPaper1'],['BPSC GS','bpscMainGS']];
let ME=null,PAGE='home',timer=null,sec=0,saveTimer=null,DATA_READY=window.DATA||{};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const msg=s=>{if($('loginMsg'))$('loginMsg').textContent=s||''};
const statusWeight=s=>s===STATUS[4]?1:s===STATUS[3]?0.78:s===STATUS[2]?0.55:s===STATUS[1]?0.25:0;
const priWeight=p=>p==='A+'?4:p==='A'?3:p==='B'?2:1;
const today=()=>new Date().toISOString().slice(0,10);
let U={status:{},targets:{},pyq:[],sessions:[],history:[],daily:120,today:0,total:0,createdAt:Date.now(),lastDay:today()};
function normalize(x){x=x||{};return Object.assign({status:{},targets:{},pyq:[],sessions:[],history:[],daily:120,today:0,total:0,createdAt:Date.now(),lastDay:today(),displayName:''},x,{status:x.status||{},targets:x.targets||{},pyq:x.pyq||[],sessions:x.sessions||[],history:x.history||[]})}
function setAuthState(text,cls=''){const e=$('authState');if(e){e.textContent=text;e.className='authstate '+cls}}
async function saveCloud(){if(!ME||!window.CS_DB)return;try{await CS_DB.collection('users').doc(ME.uid).set({...U,displayName:ME.displayName||U.displayName||$('displayName')?.value||'',email:ME.email||'',updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}catch(e){console.error(e);setAuthState('Signed in, but cloud save failed. Check Firestore rules/database.', 'err')}}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,450)}
async function loadCloud(user){ME=user;setAuthState('Signed in to Firebase ✓','ok');msg('Account authenticated successfully. Loading your cloud profile…');try{const snap=await CS_DB.collection('users').doc(user.uid).get();if(snap.exists)U=normalize(snap.data());else{U=normalize({displayName:user.displayName||$('displayName').value.trim()});await saveCloud()}if(U.lastDay!==today()){U.today=0;U.lastDay=today();queueSave()}openApp()}catch(e){console.error('[CS Master Portal] Firestore load:',e);U=normalize({displayName:user.displayName||$('displayName').value.trim()});setAuthState('Signed in to Firebase ✓','ok');msg('Authentication succeeded. Firestore needs configuration/rules; opening the portal anyway.');openApp()}}async function authAction(){const email=$('username').value.trim(),pass=$('password').value,display=$('displayName').value.trim();if(!email||!pass)return msg('Enter your email and password.');if(pass.length<6)return msg('Firebase requires a password of at least 6 characters.');if(!window.CS_FIREBASE_READY)return msg('Firebase is not initialized. Check the Firebase configuration.');const btn=$('auth');if(btn){btn.disabled=true;btn.textContent='Please wait…'}msg('Checking Firebase Authentication…');try{let cred;try{cred=await CS_AUTH.signInWithEmailAndPassword(email,pass);msg('Existing account found. Signing in…')}catch(e){if(e.code==='auth/user-not-found'){msg('No account found. Creating your Firebase account…');cred=await CS_AUTH.createUserWithEmailAndPassword(email,pass);if(display){try{await cred.user.updateProfile({displayName:display})}catch(_){}}try{await cred.user.sendEmailVerification()}catch(_){}msg('Firebase account created successfully. Opening your portal…')}else throw e}if(display&&cred.user.displayName!==display){try{await cred.user.updateProfile({displayName:display})}catch(_){} }await loadCloud(cred.user)}catch(e){console.error('[CS Master Portal] Authentication:',e);const m={'auth/wrong-password':'Incorrect password.','auth/invalid-credential':'Incorrect email or password.','auth/email-already-in-use':'This email already has a Firebase account. Use its existing password or reset the password.','auth/invalid-email':'Enter a valid email address.','auth/weak-password':'Password is too weak. Use at least 6 characters.','auth/too-many-requests':'Too many attempts. Try again later.','auth/operation-not-allowed':'Email/password Authentication is not enabled in Firebase Console.','auth/network-request-failed':'Network request failed. Check your internet connection/ad-blocker and try again.'};msg((m[e.code]||e.message||'Authentication failed.')+' ['+(e.code||'unknown')+']');setAuthState('Firebase connected ✓ — authentication error','err')}finally{if(btn){btn.disabled=false;btn.textContent='Create account / Sign in'}}}
