(()=>{
'use strict';
const $=id=>document.getElementById(id);
const STATUS=['⬜ Not Started','🟨 Studying','🟦 Notes Done','🟩 PYQ Done','⭐ Mastered'];
const EX=[['DSSSB CS','dsssbTech'],['DSSSB Paper 1','dsssbPaper1'],['BPSC CS','bpscSubject'],['BPSC Prelims','bpscPrelims'],['BPSC Paper 1','bpscMainPaper1'],['BPSC GS','bpscMainGS']];
let ME=null,PAGE='home',timer=null,sec=0,saveTimer=null,DATA_READY=window.DATA||{};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const msg=s=>{if($('loginMsg'))$('loginMsg').textContent=s||''};
const statusWeight=s=>s===STATUS[4]?1:s===STATUS[3]?0.78:s===STATUS[2]?0.55:s===STATUS[1]?0.25:0;
const priWeight=p=>p==='A+'?4:p==='A'?3:p==='B'?2:1;
const today=()=>new Date().toISOString().slice(0,10);
let U={status:{},targets:{},pyq:[],sessions:[],history:[],daily:120,today:0,total:0,createdAt:Date.now(),lastDay:today()};
function normalize(x){x=x||{};return Object.assign({status:{},targets:{},pyq:[],sessions:[],history:[],daily:120,today:0,total:0,createdAt:Date.now(),lastDay:today(),displayName:''},x,{status:x.status||{},targets:x.targets||{},pyq:x.pyq||[],sessions:x.sessions||[],history:x.history||[]})}
function setAuthState(text,cls=''){const e=$('authState');if(e){e.textContent=text;e.className='authstate '+cls}}
async function saveCloud(){if(!ME||!window.CS_DB)return;try{await CS_DB.collection('users').doc(ME.uid).set({...U,displayName:ME.displayName||U.displayName||$('displayName')?.value||'',email:ME.email||'',updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true})}catch(e){console.error(e);setAuthState('Signed in, but cloud save failed. Check Firestore rules/database.', 'err')}}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,450)}
async function loadCloud(user){ME=user;setAuthState('Signed in to Firebase ✓','ok');try{const snap=await CS_DB.collection('users').doc(user.uid).get();if(snap.exists)U=normalize(snap.data());else{U=normalize({displayName:user.displayName||$('displayName').value.trim()});await saveCloud()}if(U.lastDay!==today()){U.today=0;U.lastDay=today();queueSave()}openApp()}catch(e){console.error(e);setAuthState('Authentication works, but Firestore could not be read.','err');msg('Firebase Authentication succeeded, but Firestore is not available yet. Enable Firestore and publish the supplied security rules.')}}
async function authAction(){const email=$('username').value.trim(),pass=$('password').value,display=$('displayName').value.trim();if(!email||!pass)return msg('Enter your email and password.');if(pass.length<6)return msg('Firebase requires a password of at least 6 characters.');if(!window.CS_FIREBASE_READY)return msg('Firebase is not initialized. Check the Firebase configuration.');msg('Signing in…');try{let cred;try{cred=await CS_AUTH.signInWithEmailAndPassword(email,pass)}catch(e){if(e.code==='auth/user-not-found'){cred=await CS_AUTH.createUserWithEmailAndPassword(email,pass);if(display)await cred.user.updateProfile({displayName:display});try{await cred.user.sendEmailVerification()}catch(_){}}else throw e}if(display&&cred.user.displayName!==display)await cred.user.updateProfile({displayName:display});await loadCloud(cred.user)}catch(e){console.error(e);const m={ 'auth/wrong-password':'Incorrect password.','auth/invalid-credential':'Incorrect email or password.','auth/email-already-in-use':'That email already has an account; use the correct password.','auth/invalid-email':'Enter a valid email address.','auth/too-many-requests':'Too many attempts. Try again later.','auth/operation-not-allowed':'Email/password Authentication is not enabled in Firebase Console.'};msg(m[e.code]||e.message||'Authentication failed.')}}
async function resetPassword(){const email=$('username').value.trim();if(!email)return msg('Enter your email address first.');try{await CS_AUTH.sendPasswordResetEmail(email);msg('Password reset email sent. Check your inbox.')}catch(e){msg(e.code==='auth/user-not-found'?'No Firebase account exists for this email.':e.message)}}
async function verifyEmail(){const user=CS_AUTH?.currentUser;if(!user)return msg('Sign in first.');try{await user.sendEmailVerification();msg('Verification email sent.')}catch(e){msg(e.message)}}
function signOut(){if(timer){clearInterval(timer);timer=null}CS_AUTH.signOut();ME=null;$('app').classList.add('hide');$('login').classList.remove('hide');setAuthState(window.CS_FIREBASE_READY?'Firebase ready — sign in to continue':'Firebase unavailable','');msg('Signed out.')}
function openApp(){$('login').classList.add('hide');$('app').classList.remove('hide');$('who').textContent='👤 '+(ME.displayName||ME.email)+'  ☁ Firebase';render()}
function rowsFor(){return EX.flatMap(([exam,key])=>(DATA_READY[key]||[]).flatMap(x=>(x[3]||[]).map(topic=>({exam,section:x[0],topic,priority:x[2],id:exam+'|'+x[0]+'|'+topic}))));}
function st(id){return U.status[id]||STATUS[0]}
function setSt(id,v){const old=st(id);U.status[id]=v;U.history.push({type:'status',id,from:old,to:v,at:Date.now()});queueSave();render()}
function stats(exam){const a=rowsFor().filter(x=>x.exam===exam),den=a.reduce((n,x)=>n+priWeight(x.priority),0),score=den?Math.round(a.reduce((n,x)=>n+priWeight(x.priority)*statusWeight(st(x.id)),0)/den*100):0;return{total:a.length,done:a.filter(x=>st(x.id)===STATUS[3]||st(x.id)===STATUS[4]).length,master:a.filter(x=>st(x.id)===STATUS[4]).length,score}}
function pyqStats(exam){const q=(U.pyq||[]).filter(x=>!exam||x.e===exam),attempts=q.reduce((n,x)=>n+(+x.attempts||0),0),correct=q.reduce((n,x)=>n+(+x.correct||0),0);return{n:q.length,attempts,correct,accuracy:attempts?Math.round(correct/attempts*100):0,topics:new Set(q.map(x=>x.t)).size}}
function overall(){const a=rowsFor(),den=a.reduce((n,x)=>n+priWeight(x.priority),0),score=den?Math.round(a.reduce((n,x)=>n+priWeight(x.priority)*statusWeight(st(x.id)),0)/den*100):0,done=a.filter(x=>st(x.id)===STATUS[3]||st(x.id)===STATUS[4]).length;return{score,total:a.length,done,remaining:a.length-done,master:a.filter(x=>st(x.id)===STATUS[4]).length,pyq:pyqStats()}}
function fmtMin(m){m=Math.round(m||0);return`${Math.floor(m/60)}h ${m%60}m`}
function remain(t){let ms=new Date(t)-Date.now();if(ms<=0)return'<b>Target reached</b>';let d=Math.floor(ms/86400000);ms%=86400000;let h=Math.floor(ms/3600000);ms%=3600000;let m=Math.floor(ms/60000);return`<b>${d}d ${h}h ${m}m</b> remaining`}
function readiness(){const o=overall(),days=['dsssb','bpsc'].filter(k=>U.targets[k]).map(k=>Math.max(.25,(new Date(U.targets[k])-Date.now())/86400000));return{score:o.score,accuracy:o.pyq.accuracy,coverage:o.total?Math.round(o.pyq.topics/o.total*100):0,need:days.length?Math.ceil(o.remaining/Math.min(...days)):null}}
function priorityMap(k){return`<div class="heat">${(DATA_READY.maps?.[k]||[]).map(x=>`<div><span class="badge ${String(x[2]||'').toLowerCase().replace('+','plus')}">${esc(x[2])}</span><br><b>${esc(x[0])}</b><br><span class="small">${esc(x[1])}</span></div>`).join('')||'<span class="mut">Priority map data not loaded.</span>'}</div>`}
function home(){const r=readiness(),o=overall(),ex=EX.map(x=>x[0]);return`<div class="alert ${r.score>=75?'success':r.score<45?'dangerbox':'warning'}"><b>Weighted readiness: ${r.score}/100.</b> This is a study-readiness index, not a predicted exam score.</div><div class="grid"><div class="card"><span class="small">Overall readiness</span><div class="kpi">${r.score}%</div><div class="bar"><i style="width:${r.score}%"></i></div></div><div class="card"><span class="small">Completed / mastered</span><div class="kpi">${o.done}/${o.total}</div></div><div class="card"><span class="small">PYQ accuracy</span><div class="kpi">${r.accuracy}%</div><span class="small">${o.pyq.attempts} attempts</span></div><div class="card"><span class="small">PYQ topic coverage</span><div class="kpi">${r.coverage}%</div></div></div><div class="grid">${ex.map(e=>{const s=stats(e);return`<div class="card"><b>${esc(e)}</b><div class="kpi">${s.score}%</div><div class="bar"><i style="width:${s.score}%"></i></div><span class="small">${s.master} mastered • ${s.done} completed</span></div>`}).join('')}</div><div class="two"><div class="card"><h2>DSSSB priority map</h2>${priorityMap('dsssb')}</div><div class="card"><h2>BPSC CS priority map</h2>${priorityMap('bpscSubject')}</div></div><div class="two"><div class="card"><h2>Exam countdown</h2>${U.targets.dsssb?`DSSSB: ${remain(U.targets.dsssb)}`:'DSSSB: <span class="mut">set date</span>'}<br>${U.targets.bpsc?`BPSC: ${remain(U.targets.bpsc)}`:'BPSC: <span class="mut">set date</span>'}</div><div class="card"><h2>Study pace</h2><div class="statrow"><span>Today</span><b>${fmtMin(U.today)}</b></div><div class="statrow"><span>Total focused</span><b>${fmtMin(U.total)}</b></div><div class="statrow"><span>Daily target</span><b>${U.daily} min</b></div>${r.need?`<div class="statrow"><span>Required topic completions/day</span><b>${r.need}</b></div>`:''}</div></div>`}
function analytics(){const o=overall(),r=readiness(),high=rowsFor().filter(x=>priWeight(x.priority)>=3&&st(x.id)!==STATUS[4]).sort((a,b)=>priWeight(b.priority)-priWeight(a.priority)).slice(0,20),pat={};U.pyq.forEach(x=>pat[x.p||'Unclassified']=(pat[x.p||'Unclassified']||0)+1);return`<div class="grid"><div class="card"><span class="small">Readiness</span><div class="kpi">${r.score}/100</div></div><div class="card"><span class="small">Accuracy</span><div class="kpi">${r.accuracy}%</div></div><div class="card"><span class="small">PYQ coverage</span><div class="kpi">${r.coverage}%</div></div><div class="card"><span class="small">Focused time</span><div class="kpi">${fmtMin(U.total)}</div></div></div><div class="two"><div class="card"><h2>High-impact unfinished</h2>${high.length?high.map(x=>`<div class="statrow"><span><b>${esc(x.topic)}</b><br><span class="small">${esc(x.exam)} • ${esc(x.section)} • ${x.priority}</span></span><span>${st(x.id)}</span></div>`).join(''):'<div class="alert success">No unmastered A+/A topics.</div>'}</div><div class="card"><h2>Observed PYQ patterns</h2>${Object.entries(pat).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="statrow"><span>${esc(k)}</span><b>${v}</b></div>`).join('')||'<span class="mut">Add actual PYQs to build evidence-based pattern analytics.</span>'}</div></div><div class="card"><h2>How the analytics work</h2><ul><li><b>Readiness:</b> A+ topics carry more weight than A/B/C and stronger status earns more credit.</li><li><b>PYQ accuracy:</b> correct ÷ attempts from questions you record.</li><li><b>Coverage:</b> unique PYQ topics ÷ coded syllabus micro-topics.</li><li><b>Planner:</b> unfinished high-priority topics are surfaced first and PYQ evidence improves ranking.</li></ul></div>`}
function planner(){const r=readiness(),freq={};U.pyq.forEach(q=>freq[q.t]=(freq[q.t]||0)+1);const a=rowsFor().map(x=>({...x,rank:priWeight(x.priority)*(1-statusWeight(st(x.id)))+Math.min(1,(freq[x.topic]||0)/5)*.35}).filter(x=>st(x.id)!==STATUS[4]).sort((a,b)=>b.rank-a.rank).slice(0,25);return`<div class="alert"><b>Smart queue:</b> priority × unfinished status × observed PYQ evidence.</div><div class="card"><h2>Next best topics</h2><table><tr><th>Topic</th><th>Exam</th><th>Priority</th><th>Status</th><th>PYQ evidence</th></tr>${a.map(x=>`<tr><td><b>${esc(x.topic)}</b><br><span class="small">${esc(x.section)}</span></td><td>${esc(x.exam)}</td><td>${x.priority}</td><td>${st(x.id)}</td><td>${freq[x.topic]||0}</td></tr>`).join('')}</table></div><div class="card"><h2>Pacing</h2>${r.need?`You need roughly <b>${r.need} topic completions/day</b> before the nearest configured target date.`:'Set DSSSB/BPSC dates in Settings to calculate required pace.'}</div>`}
function syllabus(key,exam){const data=DATA_READY[key]||[];return`<div class="card"><div class="toolbar"><input id="search" placeholder="Search topic or subtopic"><select id="priority"><option value="">All priorities</option><option>A+</option><option>A</option><option>B</option><option>C</option></select><select id="statusFilter"><option value="">All statuses</option>${STATUS.map(s=>`<option>${s}</option>`).join('')}</select></div><p class="small"><b>Status:</b> ${STATUS.join(' → ')}. Every status change is stored in your cloud history.</p></div>${data.map(x=>`<section class="section"><div class="sh"><b>${esc(x[0])}</b><span class="badge ${String(x[2]||'').toLowerCase().replace('+','plus')}">${esc(x[2])}</span></div><table><tr><th>Micro-topic</th><th>Priority</th><th>Status</th></tr>${(x[3]||[]).map(t=>{const id=exam+'|'+x[0]+'|'+t,v=st(id),trap=(DATA_READY.traps||[])[(t.length+x[0].length)%Math.max(1,(DATA_READY.traps||[]).length)];return`<tr class="topicrow" data-text="${esc((x[0]+' '+t).toLowerCase())}" data-priority="${esc(x[2])}" data-status="${esc(v)}"><td><b>${esc(t)}</b>${trap?`<div class="small">⚠ ${esc(trap)}</div>`:''}</td><td>${esc(x[2])}</td><td><select class="statusSelect" data-id="${esc(id)}">${STATUS.map(s=>`<option ${s===v?'selected':''}>${s}</option>`).join('')}</select></td></tr>`}).join('')}</table></section>`}).join('')}`}
function common(){const a=new Set((DATA_READY.dsssbTech||[]).flatMap(x=>x[3]||[])),b=(DATA_READY.bpscSubject||[]).flatMap(x=>x[3]||[]).filter(x=>a.has(x));return`<div class="card"><h2>Common Core</h2><p>Concepts that overlap across DSSSB and BPSC CS. Master once, revise twice.</p><div class="heat">${b.map(x=>`<div><b>${esc(x)}</b></div>`).join('')||'<span class="mut">Common-core data not available.</span>'}</div></div>`}
function pyq(){const a=U.pyq,q=overall().pyq;return`<div class="card"><div class="toolbar"><div><h2>PYQ Bank</h2><span class="small">Question-level evidence drives analytics.</span></div><button class="primary" id="addPyq">＋ Add PYQ</button></div><div class="grid"><div class="card"><b>${a.length}</b><br><span class="small">Questions</span></div><div class="card"><b>${q.attempts}</b><br><span class="small">Attempts</span></div><div class="card"><b>${q.accuracy}%</b><br><span class="small">Accuracy</span></div><div class="card"><b>${q.topics}</b><br><span class="small">Unique topics</span></div></div>${a.length?`<table><tr><th>Exam</th><th>Year/shift</th><th>Topic</th><th>Pattern</th><th>Difficulty</th><th>Attempts</th><th>Correct</th></tr>${a.map(x=>`<tr><td>${esc(x.e)}</td><td>${esc(x.y)}</td><td>${esc(x.t)}</td><td>${esc(x.p)}</td><td>${esc(x.d)}</td><td>${x.attempts}</td><td>${x.correct}</td></tr>`).join('')}</table>`:'<div class="alert">No PYQs recorded yet. Add real questions and the portal will start building observed pattern analytics.</div>'}</div>`}
function settings(){return`<div class="two"><div class="card"><h2>Exam dates</h2><label>DSSSB<input id="dd" type="datetime-local" value="${(U.targets.dsssb||'').slice(0,16)}"></label><label>BPSC<input id="bd" type="datetime-local" value="${(U.targets.bpsc||'').slice(0,16)}"></label><button id="dates" class="primary">Save dates</button></div><div class="card"><h2>Study target</h2><input id="daily" type="number" min="1" value="${U.daily}"><button id="dailySave">Save daily minutes</button><hr><b>Account</b><p class="small">${esc(ME.email)}${ME.emailVerified?' • Email verified':' • Email not verified'}</p><button id="verify2">Send verification email</button></div></div><div class="card"><button id="export">Export local JSON backup</button></div>`}
function time(){return`<div class="grid"><div class="card"><span class="small">Current session</span><div id="tm" class="kpi">${fmtSec(sec)}</div><button id="start" class="primary">${timer?'Pause':'Start'}</button> <button id="rst">Reset</button></div><div class="card">Today<div class="kpi">${fmtMin(U.today)}</div></div><div class="card">Total focused<div class="kpi">${fmtMin(U.total)}</div></div><div class="card">Daily target<div class="kpi">${U.daily}m</div></div></div>`}
function fmtSec(s){s=Math.round(s||0);return`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m ${s%60}s`}
function render(){const titles={home:'Dashboard',analytics:'Analytics',planner:'Smart Planner',dsssb:'DSSSB TGT Computer Science',d1:'DSSSB Paper 1',bpsc:'BPSC TRE 4.0 Computer Science',b1:'BPSC Paper 1',bg:'BPSC GS / Prelims',common:'Common Core',pyq:'PYQ Bank',time:'Time & Sessions',settings:'Settings'};$('title').textContent=titles[PAGE]||'Dashboard';let v=PAGE==='home'?home():PAGE==='analytics'?analytics():PAGE==='planner'?planner():PAGE==='dsssb'?syllabus('dsssbTech','DSSSB CS'):PAGE==='d1'?syllabus('dsssbPaper1','DSSSB Paper 1'):PAGE==='bpsc'?syllabus('bpscSubject','BPSC CS'):PAGE==='b1'?syllabus('bpscMainPaper1','BPSC Paper 1'):PAGE==='bg'?syllabus('bpscPrelims','BPSC Prelims'):PAGE==='common'?common():PAGE==='pyq'?pyq():PAGE==='time'?time():settings();$('content').innerHTML=v;bind()}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{PAGE=b.dataset.page;render()});document.querySelectorAll('.statusSelect').forEach(s=>s.onchange=()=>setSt(s.dataset.id,s.value));const se=$('search'),pr=$('priority'),sf=$('statusFilter');if(se&&pr&&sf){const f=()=>document.querySelectorAll('.topicrow').forEach(r=>r.style.display=(!se.value||r.dataset.text.includes(se.value.toLowerCase()))&&(!pr.value||r.dataset.priority===pr.value)&&(!sf.value||r.dataset.status===sf.value)?'':'none');se.oninput=f;pr.onchange=f;sf.onchange=f}if($('addPyq'))$('addPyq').onclick=()=>{const e=prompt('Exam'),y=prompt('Year / shift'),t=prompt('Topic / subtopic'),p=prompt('Pattern'),d=prompt('Difficulty'),a=prompt('Attempts','1'),c=prompt('Correct','0');if(e&&y&&t){U.pyq.push({e,y,t,p,d,attempts:+a||0,correct:+c||0,at:Date.now()});queueSave();render()}};if($('dates'))$('dates').onclick=()=>{U.targets={dsssb:$('dd').value,bpsc:$('bd').value};queueSave();render()};if($('dailySave'))$('dailySave').onclick=()=>{U.daily=Math.max(1,+$('daily').value||120);queueSave();render()};if($('start'))$('start').onclick=toggle;if($('rst'))$('rst').onclick=()=>{sec=0;render()};if($('export'))$('export').onclick=()=>{const a=document.createElement('a'),b=new Blob([JSON.stringify(U,null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download='cs-teacher-master-backup.json';a.click()};if($('verify2'))$('verify2').onclick=verifyEmail}
function toggle(){if(timer){clearInterval(timer);timer=null;U.sessions.push({at:Date.now(),seconds:sec});queueSave();render()}else{timer=setInterval(()=>{sec++;U.today+=1/60;U.total+=1/60;const e=$('tm');if(e)e.textContent=fmtSec(sec)},1000);render()}}
$('auth').onclick=authAction;$('resetPassword').onclick=resetPassword;$('verify').onclick=verifyEmail;$('lock').onclick=signOut;$('password').onkeydown=e=>{if(e.key==='Enter')authAction()};
if(window.CS_FIREBASE_READY){setAuthState('Firebase connected ✓','ok');CS_AUTH.onAuthStateChanged(user=>{if(user)loadCloud(user);});}else setAuthState('Firebase configuration unavailable','err');
})();