(() => {
'use strict';
const $=id=>document.getElementById(id);
const STATUS=['⬜ Not Started','🟨 Studying','🟦 Notes Done','🟩 PYQ Done','⭐ Mastered'];
const STORE='cs-teacher-master-v10';
let DB={users:{}};
try{const raw=localStorage.getItem(STORE);if(raw){const x=JSON.parse(raw);if(x&&x.users)DB=x;}}catch(e){localStorage.removeItem(STORE);}
let ME='',PAGE='home',timer=null,elapsed=0;
const save=()=>{try{localStorage.setItem(STORE,JSON.stringify(DB));}catch(e){alert('Browser storage is unavailable. Please allow site storage.');}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const u=()=>DB.users[ME];
function simpleHash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16);}
function badge(p){return String(p||'').toLowerCase().replace('+','plus');}
function profileButtons(){const el=$('userButtons');if(!el)return;el.innerHTML=Object.keys(DB.users).map(n=>`<button type="button" data-user="${esc(n)}">${esc(n)}</button>`).join('');el.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{$('username').value=b.dataset.user;$('password').focus();});}
function showLogin(msg=''){ $('app').classList.add('hide');$('login').classList.remove('hide');$('loginMsg').textContent=msg;profileButtons(); }
function signIn(){
 const n=$('username').value.trim(),pw=$('password').value;
 if(!n||!pw){$('loginMsg').textContent='Enter both profile name and password.';return;}
 try{
  const hash=simpleHash(pw),existing=DB.users[n];
  if(!existing){DB.users[n]={hash,status:{},targets:{},today:0,total:0,daily:120,pyq:[],reminderHour:20,lastDay:new Date().toISOString().slice(0,10)};save();ME=n;openApp();return;}
  if(existing.hash!==hash){$('loginMsg').textContent='Incorrect password. If this is an old profile, use Reset profile and create it again.';return;}
  ME=n;openApp();
 }catch(e){$('loginMsg').textContent='Login error: '+e.message;}
}
function openApp(){const x=u();const today=new Date().toISOString().slice(0,10);if(x.lastDay!==today){x.today=0;x.lastDay=today;save();}$('login').classList.add('hide');$('app').classList.remove('hide');$('who').textContent='👤 '+ME;render();}
function resetProfile(){const n=$('username').value.trim();if(!n){$('loginMsg').textContent='Enter the profile name you want to reset.';return;}if(!DB.users[n]){$('loginMsg').textContent='No such profile exists.';return;}if(confirm('Delete the local profile "'+n+'" and all its study data?')){delete DB.users[n];save();$('password').value='';$('loginMsg').textContent='Profile deleted. Create it again with your new password.';profileButtons();}}
function lock(){if(timer){clearInterval(timer);timer=null;}ME='';showLogin('Locked. Select a profile or create a new one.');}
function rowsFor(){return [['DSSSB CS',DATA.dsssbTech],['DSSSB Paper 1',DATA.dsssbPaper1],['BPSC CS',DATA.bpscSubject],['BPSC Prelims',DATA.bpscPrelims],['BPSC Paper 1',DATA.bpscMainPaper1],['BPSC GS',DATA.bpscMainGS]].flatMap(([exam,a])=>a.flatMap(x=>x[3].map(t=>({exam,section:x[0],topic:t,priority:x[2],id:exam+'|'+x[0]+'|'+t}))));}
function st(id){return u().status[id]||STATUS[0];}
function setSt(id,v){u().status[id]=v;save();}
function stats(exam){const a=rowsFor().filter(x=>x.exam===exam),done=a.filter(x=>st(x.id)===STATUS[3]||st(x.id)===STATUS[4]).length,master=a.filter(x=>st(x.id)===STATUS[4]).length;return [a.length,done,master,a.length?Math.round(done/a.length*100):0];}
function fmt(sec){sec=Math.round(sec||0);return `${Math.floor(sec/3600)}h ${Math.floor(sec%3600/60)}m ${sec%60}s`;}
function remain(t){let ms=new Date(t)-Date.now();if(ms<=0)return '<b>Target reached</b>';let d=Math.floor(ms/86400000);ms%=86400000;let h=Math.floor(ms/3600000);ms%=3600000;let m=Math.floor(ms/60000);return `<b>${d}d ${h}h ${m}m</b> remaining`;}
function priorityMap(key){return `<div class="heat">${(DATA.maps[key]||[]).map(x=>`<div><span class="badge ${badge(x[2])}">${esc(x[2])}</span><br><b>${esc(x[0])}</b><br><span class="small">${esc(x[1])}</span></div>`).join('')}</div>`;}
function home(){const exams=['DSSSB CS','DSSSB Paper 1','BPSC CS','BPSC Prelims','BPSC Paper 1','BPSC GS'],ss=exams.map(stats),total=ss.reduce((a,x)=>a+x[0],0),done=ss.reduce((a,x)=>a+x[1],0);return `<div class="grid">${[['Micro-topics',total],['PYQ Done',done],['Mastered',ss.reduce((a,x)=>a+x[2],0)],['Overall',Math.round(done/total*100)+'%']].map(x=>`<div class="card"><span class="small">${x[0]}</span><div class="kpi">${x[1]}</div></div>`).join('')}</div><div class="grid">${exams.map((e,i)=>`<div class="card"><b>${e}</b><div class="kpi">${ss[i][3]}%</div><div class="bar"><i style="width:${ss[i][3]}%"></i></div><span class="small">${ss[i][1]}/${ss[i][0]} PYQ/mastered</span></div>`).join('')}</div><div class="two"><div class="card"><h2>DSSSB priority map</h2>${priorityMap('dsssb')}</div><div class="card"><h2>BPSC CS priority map</h2>${priorityMap('bpscSubject')}</div></div><div class="two"><div class="card"><h2>Countdown</h2>${u().targets.dsssb?`DSSSB: ${remain(u().targets.dsssb)}`:'DSSSB: <span class="mut">set date in Settings</span>'}<br>${u().targets.bpsc?`BPSC: ${remain(u().targets.bpsc)}`:'BPSC: <span class="mut">set date in Settings</span>'}</div><div class="card"><h2>Today</h2><div class="kpi">${fmt((u().today||0)*60)}</div><span class="small">Target: ${u().daily||120} minutes</span><div class="bar"><i style="width:${Math.min(100,(u().today||0)/(u().daily||120)*100)}%"></i></div></div></div><div class="alert"><b>Priority rule:</b> A+ → A → B/C. A topic becomes truly complete only after notes + PYQs + recall.</div>`;}
function syllabus(key,exam){return `<div class="card"><div class="toolbar"><input id="search" placeholder="Search topic or subtopic"><select id="priority"><option value="">All priorities</option><option>A+</option><option>A</option><option>B</option><option>C</option></select><select id="statusFilter"><option value="">All statuses</option>${STATUS.map(s=>`<option>${s}</option>`).join('')}</select></div></div>${DATA[key].map(x=>`<section class="section"><div class="sh"><b>${esc(x[0])}</b><span class="badge ${badge(x[2])}">${esc(x[2])}</span></div><table><tr><th>Micro-topic</th><th>Status</th></tr>${x[3].map(t=>{const id=exam+'|'+x[0]+'|'+t,v=st(id);return `<tr class="topicrow ${v===STATUS[4]?'master':''}" data-text="${esc((x[0]+' '+t).toLowerCase())}" data-priority="${esc(x[2])}" data-status="${esc(v)}"><td><b>${esc(t)}</b><div class="small">⚠ ${esc(DATA.traps[(t.length+x[0].length)%DATA.traps.length])}</div></td><td><select class="statusSelect" data-id="${esc(id)}">${STATUS.map(s=>`<option ${s===v?'selected':''}>${s}</option>`).join('')}</select></td></tr>`;}).join('')}</table></section>`).join('')}`;}
function common(){const a=new Set(DATA.dsssbTech.flatMap(x=>x[3]));const b=DATA.bpscSubject.flatMap(x=>x[3]).filter(x=>a.has(x));return `<div class="card"><h2>Common Core</h2><p>Master these concepts once and reuse them across DSSSB + BPSC.</p><div class="heat">${b.map(x=>`<div><b>${esc(x)}</b></div>`).join('')}</div></div>`;}
function pyq(){const a=u().pyq||[];return `<div class="card"><h2>PYQ Bank</h2><p class="small">Record question-level evidence here. We will use these records for real topic-frequency calculations.</p><button class="primary" id="addPyq">＋ Add PYQ</button>${a.length?`<table><tr><th>Exam</th><th>Year/Shift</th><th>Topic</th><th>Pattern</th><th>Difficulty</th></tr>${a.map(x=>`<tr><td>${esc(x.e)}</td><td>${esc(x.y)}</td><td>${esc(x.t)}</td><td>${esc(x.p)}</td><td>${esc(x.d)}</td></tr>`).join('')}</table>`:'<p class="mut">No PYQs coded yet.</p>'}</div>`;}
function timePage(){return `<div class="grid"><div class="card"><span class="small">Current focus</span><div class="kpi" id="focusTimer">${fmt(elapsed)}</div><button class="primary" id="timerBtn">${timer?'Pause':'Start'}</button> <button id="resetTimer">Reset</button></div><div class="card"><span class="small">Today</span><div class="kpi">${fmt((u().today||0)*60)}</div></div><div class="card"><span class="small">Total focused</span><div class="kpi">${fmt((u().total||0)*60)}</div></div><div class="card"><span class="small">Daily target (min)</span><input id="dailyTarget" type="number" min="1" value="${u().daily||120}"><button id="saveDaily">Save</button></div></div>`;}
function settings(){const t=u().targets||{};return `<div class="two"><div class="card"><h2>Exam dates</h2><label>DSSSB<input id="dDate" type="datetime-local" value="${(t.dsssb||'').slice(0,16)}"></label><label>BPSC<input id="bDate" type="datetime-local" value="${(t.bpsc||'').slice(0,16)}"></label><button class="primary" id="saveDates">Save dates</button></div><div class="card"><h2>Reminder</h2><button class="primary" id="notify">Enable browser notifications</button><label>Reminder hour<input id="remHour" type="number" min="0" max="23" value="${u().reminderHour??20}"></label><button id="saveReminder">Save</button><p class="small">Notifications work while this page is open. For guaranteed background alerts we can add a server/automation layer later.</p></div></div><div class="card"><h2>Profile: ${esc(ME)}</h2><button class="danger" id="deleteProfile">Delete profile</button></div>`;}
function render(){const titles={home:'Dashboard',dsssb:'DSSSB TGT Computer Science',d1:'DSSSB Paper 1',bpsc:'BPSC TRE 4.0 Computer Science',b1:'BPSC Paper 1',bg:'BPSC GS / Prelims',common:'Common Core',pyq:'PYQ Bank',time:'Time & Planner',settings:'Settings'};$('title').textContent=titles[PAGE];let html=PAGE==='home'?home():PAGE==='dsssb'?syllabus('dsssbTech','DSSSB CS'):PAGE==='d1'?syllabus('dsssbPaper1','DSSSB Paper 1'):PAGE==='bpsc'?syllabus('bpscSubject','BPSC CS'):PAGE==='b1'?syllabus('bpscMainPaper1','BPSC Paper 1'):PAGE==='bg'?syllabus('bpscPrelims','BPSC Prelims'):PAGE==='common'?common():PAGE==='pyq'?pyq():PAGE==='time'?timePage():settings();$('content').innerHTML=html;bind();}
function bind(){
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{PAGE=b.dataset.page;render();});
 document.querySelectorAll('.statusSelect').forEach(s=>s.onchange=()=>{setSt(s.dataset.id,s.value);render();});
 const search=$('search'),pr=$('priority'),sf=$('statusFilter');if(search&&pr&&sf){const f=()=>document.querySelectorAll('.topicrow').forEach(r=>r.style.display=(!search.value||r.dataset.text.includes(search.value.toLowerCase()))&&(!pr.value||r.dataset.priority===pr.value)&&(!sf.value||r.dataset.status===sf.value)?'':'none');search.oninput=pr.onchange=sf.onchange=f;}
 if($('addPyq'))$('addPyq').onclick=()=>{const e=prompt('Exam?'),y=prompt('Year / shift?'),t=prompt('Topic/subtopic?'),p=prompt('Pattern?'),d=prompt('Difficulty?');if(e&&y&&t){u().pyq.push({e,y,t,p:p||'',d:d||''});save();render();}};
 if($('timerBtn'))$('timerBtn').onclick=toggleTimer;if($('resetTimer'))$('resetTimer').onclick=()=>{elapsed=0;render();};
 if($('saveDaily'))$('saveDaily').onclick=()=>{u().daily=Math.max(1,+$('dailyTarget').value||120);save();render();};
 if($('saveDates'))$('saveDates').onclick=()=>{u().targets={dsssb:$('dDate').value,bpsc:$('bDate').value};save();render();};
 if($('notify'))$('notify').onclick=async()=>{if(!('Notification'in window)){alert('Notifications are not supported here.');return;}const r=await Notification.requestPermission();alert(r==='granted'?'Notifications enabled.':'Permission not granted.');};
 if($('saveReminder'))$('saveReminder').onclick=()=>{u().reminderHour=Math.max(0,Math.min(23,+$('remHour').value||20));save();alert('Reminder setting saved.');};
 if($('deleteProfile'))$('deleteProfile').onclick=()=>{if(confirm('Delete this profile and all its local data?')){delete DB.users[ME];save();lock();}};
}
function toggleTimer(){if(timer){clearInterval(timer);timer=null;render();return;}timer=setInterval(()=>{elapsed++;u().today=(u().today||0)+1/60;u().total=(u().total||0)+1/60;save();const x=$('focusTimer');if(x)x.textContent=fmt(elapsed);},1000);render();}
function reminder(){if(!ME)return;const h=new Date().getHours();if(h!==(u().reminderHour??20)||!('Notification'in window)||Notification.permission!=='granted')return;const key=new Date().toISOString().slice(0,13);if(u().lastReminder===key)return;u().lastReminder=key;save();const ss=['DSSSB CS','DSSSB Paper 1','BPSC CS','BPSC Prelims','BPSC Paper 1','BPSC GS'].map(stats),total=ss.reduce((a,x)=>a+x[0],0),done=ss.reduce((a,x)=>a+x[1],0);new Notification('CS Teacher Study Reminder',{body:`${Math.round(done/total*100)}% syllabus done; ${total-done} micro-topics remaining. DSSSB ${u().targets.dsssb?remain(u().targets.dsssb).replace(/<[^>]*>/g,''):'date not set'}. BPSC ${u().targets.bpsc?remain(u().targets.bpsc).replace(/<[^>]*>/g,''):'date not set'}.`});}
$('auth').addEventListener('click',signIn);$('resetProfile').addEventListener('click',resetProfile);$('lock').addEventListener('click',lock);$('password').addEventListener('keydown',e=>{if(e.key==='Enter')signIn();});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{PAGE=b.dataset.page;render();});
setInterval(()=>{if(ME){$('clock').textContent=new Date().toLocaleString();reminder();}},30000);profileButtons();
})();